# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT Forms\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 430)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 230, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(390, 360, 181, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_ok = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_ok.setObjectName("btn_ok")
        self.end_buttons = QtWidgets.QButtonGroup(Form)
        self.end_buttons.setObjectName("end_buttons")
        self.end_buttons.addButton(self.btn_ok)
        self.horizontalLayout_2.addWidget(self.btn_ok)
        self.btn_canel = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_canel.setObjectName("btn_canel")
        self.end_buttons.addButton(self.btn_canel)
        self.horizontalLayout_2.addWidget(self.btn_canel)
        self.file_name_place = QtWidgets.QPlainTextEdit(Form)
        self.file_name_place.setGeometry(QtCore.QRect(20, 280, 561, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.file_name_place.setFont(font)
        self.file_name_place.setReadOnly(True)
        self.file_name_place.setPlainText("")
        self.file_name_place.setObjectName("file_name_place")
        self.file_combo = QtWidgets.QComboBox(Form)
        self.file_combo.setGeometry(QtCore.QRect(20, 140, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.file_combo.setFont(font)
        self.file_combo.setObjectName("file_combo")
        self.is_file = QtWidgets.QLabel(Form)
        self.is_file.setGeometry(QtCore.QRect(30, 370, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(False)
        self.is_file.setFont(font)
        self.is_file.setText("")
        self.is_file.setIndent(5)
        self.is_file.setObjectName("is_file")
        self.btn_select_file = QtWidgets.QPushButton(Form)
        self.btn_select_file.setGeometry(QtCore.QRect(20, 80, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_select_file.setFont(font)
        self.btn_select_file.setObjectName("btn_select_file")
        self.btn_last_images = QtWidgets.QPushButton(Form)
        self.btn_last_images.setGeometry(QtCore.QRect(310, 80, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_last_images.setFont(font)
        self.btn_last_images.setObjectName("btn_last_images")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 551, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_actions = QtWidgets.QPushButton(Form)
        self.btn_actions.setGeometry(QtCore.QRect(510, 140, 71, 31))
        self.btn_actions.setObjectName("btn_actions")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Abobe Photoshop - Выбор картинки"))
        self.label_2.setText(_translate("Form", "Выбранный файл:"))
        self.btn_ok.setText(_translate("Form", "ОК"))
        self.btn_canel.setText(_translate("Form", "Отмена"))
        self.btn_select_file.setText(_translate("Form", "Выбрать файл"))
        self.btn_last_images.setText(_translate("Form", "Недавние изображения"))
        self.label.setText(_translate("Form", "Выберите картинку:"))
        self.btn_actions.setText(_translate("Form", "Действия"))
